#!/bin/bash

APP="$1"; IMAGE="dokku/$APP"
echo "-----> Building Grunt app ..."
COMMAND=$(cat <<EOF
cd "/app/static" &&
npm install -g grunt &&
npm install -g grunt-cli &&
npm install bower &&
npm update &&
npm install &&
grunt build --force &&
grunt prod --force
EOF
)

id=$(docker run -d $IMAGE /bin/bash -c "$COMMAND")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo "-----> Built Grunt"
